FROM node:lts-slim as build-stage
LABEL maintainer="Mael FOSSO"
RUN apt update &&  apt-get install -y \
  curl \
  iputils-ping \
  && rm -rf /var/lib/apt/lists/*
  
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 8080
CMD ["npm", "run", "serve"]
